sudo: required

services:
- docker

before_install:
- docker build -f build/Dockerfile -t rest .
- docker run -v "$(pwd)":/var/www --name rest -d rest

script:
- docker exec rest vendor/bin/codecept run  --coverage --coverage-xml --coverage-html